[tool.poetry]
name = "sexypy"
version = "0.1.0"
description = "Python with S-expression Grammar"
authors = ["Jethack"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
hy = "0.25"
hyrule = "0.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
